version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'    # RabbitMQ üçün default port
      - '15672:15672'  # RabbitMQ management UI üçün port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile  # Proyektin Dockerfile faylı ilə Spring Boot tətbiqini yığır
    ports:
      - '8080:8080'  # Tədbiqin portu
    depends_on:
      - rabbitmq  # Tətbiq RabbitMQ konteynerindən asılıdır, o başlamazdan əvvəl rabbitmq başlamalıdır.
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Profil təyin edin, əgər profil varsa varsa
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
